### ISSUE TITLE
Request for file removal: Matter-Bold.ttf

### ISSUE THREAD

**Issue by displaay** [devmer/devmer.github.io#1]
When using http://www.getthefont.com/, I found your font file [Matter-Bold.ttf](http://github.com/devmer/devmer.github.io/blob/67df90af4df92f9555705227ea1a956a3a941ebe/Bold-2/Matter-Bold.ttf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by devmer** [comment]
whoops, sorry about that! just now seeing these
